<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Amarin</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>jeklE-removebg-preview_1.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="jeklE-removebg-preview_1.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
    <PackageReference Include="System.Management" Version="9.0.4" />
    <PackageReference Include="PDFsharp" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>